# Lokal udvikling med host-porte:
# docker compose -f docker-compose.yml -f docker-compose.local.yml up --build

services:
  db:
    ports:
      - "5432:5432"

  api:
    ports:
      - "8000:8000"

  web:
    ports:
      - "3000:3000"

networks:
  dokploy-network:
    external: false
  default:
    ipam:
      config:
        - subnet: 10.42.81.0/24
