# Этап сборки (Build)
FROM node:18-alpine AS builder

WORKDIR /app

# Копируем package.json и package-lock.json из папки frontend
COPY frontend/package*.json ./

RUN npm install

# Копируем исходники фронтенда
COPY frontend/ .

# Собираем приложение
RUN npm run build

# Этап Nginx (Production server)
FROM nginx:alpine

# Копируем собранные файлы из первого этапа в директорию Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Копируем конфигурацию nginx с проксированием и SPA роутингом:
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
