"""multi_pass_scraper

Revision ID: 2e8a588002b6
Revises: 93498c7c5cdc
Create Date: 2026-08-11 13:35:03.929826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e8a588002b6'
down_revision: Union[str, Sequence[str], None] = '93498c7c5cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_datasource_url')
    )
    op.create_table('geography_grid',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_code', 'region_name', name='uq_geo_region')
    )
    op.create_table('raw_scrape_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('extracted_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('scrape_errors')
    op.add_column('hype_analysis', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_hype_analysis_status'), 'hype_analysis', ['status'], unique=False)
    op.add_column('job_postings', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.add_column('salary_data', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_salary_data_status'), 'salary_data', ['status'], unique=False)
    op.add_column('tech_trends', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_tech_trends_status'), 'tech_trends', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_trends_status'), table_name='tech_trends')
    op.drop_column('tech_trends', 'status')
    op.drop_index(op.f('ix_salary_data_status'), table_name='salary_data')
    op.drop_column('salary_data', 'status')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_column('job_postings', 'status')
    op.drop_index(op.f('ix_hype_analysis_status'), table_name='hype_analysis')
    op.drop_column('hype_analysis', 'status')
    op.create_table('scrape_errors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('error_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('scrape_errors_pkey'))
    )
    op.drop_table('source_logs')
    op.drop_table('raw_scrape_data')
    op.drop_table('geography_grid')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
