"""initial_migration

Revision ID: 93498c7c5cdc
Revises: 
Create Date: 2026-08-03 08:28:17.331282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93498c7c5cdc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ats_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=200), nullable=False),
    sa.Column('ats_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain', 'ats_type', name='uq_ats_domain')
    )
    op.create_table('hype_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'topic', name='uq_hype_date_topic')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('technology', sa.String(length=100), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'company', 'source', name='uq_job_title_company'),
    sa.UniqueConstraint('url', name='uq_job_url')
    )
    op.create_index('idx_job_country', 'job_postings', ['country'], unique=False)
    op.create_index('idx_job_date', 'job_postings', ['date'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title', 'source', name='uq_news_title_source'),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    op.create_index('idx_news_created', 'news_items', ['created_at'], unique=False)
    op.create_table('salary_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('median', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology', 'country', 'source', 'date', name='uq_salary')
    )
    op.create_index('idx_salary_tech', 'salary_data', ['technology'], unique=False)
    op.create_table('scrape_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_syslog_component', 'system_logs', ['component'], unique=False)
    op.create_index('idx_syslog_created', 'system_logs', ['created_at'], unique=False)
    op.create_index('idx_syslog_level', 'system_logs', ['level'], unique=False)
    op.create_table('tech_trends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('technology', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technology', 'country', 'source', 'date', name='uq_trend')
    )
    op.create_index('idx_trend_date', 'tech_trends', ['date'], unique=False)
    op.create_index('idx_trend_tech', 'tech_trends', ['technology'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trend_tech', table_name='tech_trends')
    op.drop_index('idx_trend_date', table_name='tech_trends')
    op.drop_table('tech_trends')
    op.drop_index('idx_syslog_level', table_name='system_logs')
    op.drop_index('idx_syslog_created', table_name='system_logs')
    op.drop_index('idx_syslog_component', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('scrape_errors')
    op.drop_index('idx_salary_tech', table_name='salary_data')
    op.drop_table('salary_data')
    op.drop_index('idx_news_created', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('idx_job_date', table_name='job_postings')
    op.drop_index('idx_job_country', table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_table('hype_analysis')
    op.drop_table('ats_companies')
    # ### end Alembic commands ###
