"""sync models

Revision ID: fb2592fb5608
Revises: add_admin_tables
Create Date: 2026-09-01 12:30:12.636252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2592fb5608'
down_revision: Union[str, Sequence[str], None] = 'add_admin_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ai_model_configs', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_aimodel_active', 'ai_model_configs', ['is_active'], unique=False)
    op.create_index('idx_aimodel_task', 'ai_model_configs', ['task_type'], unique=False)
    op.create_unique_constraint('uq_ai_model_config', 'ai_model_configs', ['task_type', 'model_name', 'provider'])
    op.add_column('data_sources', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_datasource_active', 'data_sources', ['is_active'], unique=False)
    op.create_index('idx_datasource_category', 'data_sources', ['category'], unique=False)
    op.drop_index(op.f('ix_hype_analysis_status'), table_name='hype_analysis')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_salary_data_status'), table_name='salary_data')
    op.create_index('idx_sourcelog_created', 'source_logs', ['created_at'], unique=False)
    op.create_index('idx_sourcelog_source', 'source_logs', ['data_source_id'], unique=False)
    op.drop_index(op.f('ix_tech_trends_status'), table_name='tech_trends')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tech_trends_status'), 'tech_trends', ['status'], unique=False)
    op.drop_index('idx_sourcelog_source', table_name='source_logs')
    op.drop_index('idx_sourcelog_created', table_name='source_logs')
    op.create_index(op.f('ix_salary_data_status'), 'salary_data', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_hype_analysis_status'), 'hype_analysis', ['status'], unique=False)
    op.drop_index('idx_datasource_category', table_name='data_sources')
    op.drop_index('idx_datasource_active', table_name='data_sources')
    op.drop_column('data_sources', 'updated_at')
    op.drop_constraint('uq_ai_model_config', 'ai_model_configs', type_='unique')
    op.drop_index('idx_aimodel_task', table_name='ai_model_configs')
    op.drop_index('idx_aimodel_active', table_name='ai_model_configs')
    op.drop_column('ai_model_configs', 'updated_at')
    op.drop_table('scrape_errors')
    # ### end Alembic commands ###
